//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace xc
{
    public abstract class IActorBehavior
    {
        protected Actor mOwner;
        protected bool mIsDestroy = false;
        public abstract void InitBehaviors();
        public abstract void Update();
        public abstract void LateUpdate();
        public virtual void UnInitBehaviors()
        {
            mOwner = null;
            mIsDestroy = true;
        }

        public abstract void EnableBehaviors(bool enable);
    }
}

