//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace xc.ui
{
    public class UITipBoard :MonoBehaviour
    {
        public UILabel contentLabel { get; set; }
        public UILabel titleLabel { get; set; }
        public UIButton returnButton { get; set; }

        private static UITipBoard Instance;

        private void Awake()
        {
            Instance = this;
        }

        public static void Show(string title, string content)
        {

            UIManager.Instance.ShowWindow<UIWndTipBoard>();
            UITipBoard.Instance.titleLabel.text = title;
            UITipBoard.Instance.contentLabel.text = content;
        }

        public void OnReturn()
        {
            UIManager.Instance.HideWindow<UIWndTipBoard>();
        }
    }
}

