//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using xc;
namespace xc.ui
{
    public class UIWildEvilIcon : MonoBehaviour
    {
        public UISprite IConvertible { get; set; }

        void Update()
        {
            uint sin_value= 0;
            var local_player = Game.GetInstance().GetLocalPlayer();
            if (local_player != null)
                sin_value = local_player.ActorAttribute.Sin;
            else
                sin_value = LocalPlayerManager.Instance.LocalActorAttribute.Sin;
            if (sin_value >= DBEvilBuff.lowest)
            {
                IConvertible.spriteName = "button_xuruo2";
            }
            else
            {
                IConvertible.spriteName = "button_xuruo1";
            }
        }

        public void OnClickBtn()
        {
            StartCoroutine(UIManager.Instance.ShowWindow("UIWildEvil"));
        }
    }
}

