//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace xc.ui
{
    public class UIWildTip : MonoBehaviour
    {
        public static readonly string mPrefabName = "UIEvilTip";

        public UILabel timeCountDown { get; set; }

        private float lastShowTime = 0;

        void OnEnable()
        {
            lastShowTime = Time.fixedTime;
        }

        void OnDisable()
        {
            lastShowTime = 0;
        }

        void Update()
        {

            if (lastShowTime != 0 && Time.fixedTime - lastShowTime > 5)
            {
                UIManager.Instance.HideWindow<UIWildTip>();
            }
            else
            {
                timeCountDown.text = string.Format("{0}", Mathf.CeilToInt(5-(Time.fixedTime - lastShowTime)));
            }
        }

        public void OnClick()
        {
            UIManager.Instance.HideWindow<UIWildTip>();
            StartCoroutine(UIManager.Instance.ShowWindow("UIWildEvil"));
        }
    }
}

