//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace xc.ui
{
    public class UIWildEvilItem :MonoBehaviour
    {
        public byte id;
        public UILabel price { get; set; }
        public UILabel buy { get; set; }
        public UIButton btnBuy { get; set; }
        public UILabel decrease { get; set; }
        private uint priceWhiteGold;
        private uint priceDiamond;
        public void Awake()
        {
            var lst = DBManager.Instance.GetDB<DBEvilShop>().mData;
            if (!lst.ContainsKey(id))
            {
                Debug.LogError(string.Format("evile shop id {0} not exist",id));
                return;
            }

            var data = lst [id];
            priceWhiteGold = data.priceWhiteGold;
            priceDiamond = data.priceDiamond;
            decrease.text = string.Format("{0}", data.decrease);
            price.text = string.Format("{0}", data.priceWhiteGold);
            SetTimes(0);
        }

        public void SetTimes(uint times)
        {
            var lst = DBManager.Instance.GetDB<DBEvilShop>().mData;
            if (!lst.ContainsKey(id))
            {
                Debug.LogError(string.Format("evile shop id {0} not exist",id));
                return;
            }
            
            var data = lst [id];

            buy.text = string.Format("{0}({1}/{2})", DBConstText.GetText("BUY"), times, data.dailyLimit);
            btnBuy.isEnabled = times > 0;
        }

        public void OnBuy()
        {
            UIWildEvil.Instance.BuyGood(id, priceWhiteGold, priceDiamond);
        }

    }
}

